/**
 * Step 2 — Days and Weeks (§11.1).
 *
 * The days shown are the ones the draft suggests, already assigned — from a
 * file that declared them, or from what was chosen while authoring here. The
 * user confirms or changes them, and sets how long the programme runs. Accepting
 * turns both into Placements, which are the user's from that moment on — the
 * suggested days are never read again (§12).
 *
 * The schedule below the controls is generated by the same function that will
 * run at Accept, so what is previewed is what gets written.
 */

import { Minus, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { parseLocalDate, type LocalDate } from '@/domain/dates';
import { toId, type RoutineId, type WorkoutId } from '@/domain/ids';
import type { RoutineFile, SemanticIssue } from '@/domain/routine-file';
import { generatePlacements } from '@/domain/scheduling';
import type { Weekday, Workout } from '@/domain/types';
import { describeIssue, fieldId, workoutPath } from '@/features/import/issues';
import { MAX_WEEKS, MIN_WEEKS } from '@/features/import/state';
import {
  FOCUS_RING,
  ICON_STROKE,
  LABEL,
  PRESS,
  WELL,
  chip,
} from '@/features/ui/styles';
import { cn } from '@/lib/utils';

const WEEKDAYS: readonly { readonly day: Weekday; readonly short: string }[] = [
  { day: 'monday', short: 'mon' },
  { day: 'tuesday', short: 'tue' },
  { day: 'wednesday', short: 'wed' },
  { day: 'thursday', short: 'thu' },
  { day: 'friday', short: 'fri' },
  { day: 'saturday', short: 'sat' },
  { day: 'sunday', short: 'sun' },
];

interface ScheduleStepProps {
  readonly file: RoutineFile;
  readonly issues: readonly SemanticIssue[];
  readonly today: LocalDate;
  readonly onWeeksBy: (delta: number) => void;
  readonly onToggleDay: (workoutIndex: number, day: Weekday) => void;
}

export function ScheduleStep({ file, issues, today, onWeeksBy, onToggleDay }: ScheduleStepProps) {
  const weeks = file.routine.weeks;
  const placements = previewPlacements(file, today);
  const first = placements[0]?.date;
  const last = placements[placements.length - 1]?.date;

  return (
    <>
      <p className="type-lede text-ink-2">
        These are the days this routine suggests. Change them if your week looks different.
      </p>

      <Card>
        <div className="flex items-center justify-between gap-4">
          <span className={LABEL}>weeks</span>
          <div className="flex items-center gap-3">
            <Button
              aria-label="One week fewer"
              disabled={weeks <= MIN_WEEKS}
              onClick={() => onWeeksBy(-1)}
              size="icon"
              type="button"
              variant="secondary"
            >
              <Minus aria-hidden="true" size={20} strokeWidth={ICON_STROKE} />
            </Button>
            <output
              aria-label={`${weeks} weeks`}
              className="min-w-14 rounded-field bg-well px-3 py-2 text-center type-readout"
            >
              {weeks}
            </output>
            <Button
              aria-label="One week more"
              disabled={weeks >= MAX_WEEKS}
              onClick={() => onWeeksBy(1)}
              size="icon"
              type="button"
              variant="secondary"
            >
              <Plus aria-hidden="true" size={20} strokeWidth={ICON_STROKE} />
            </Button>
          </div>
        </div>
      </Card>

      {file.routine.workouts.map((workout, index) => {
        // A day this Workout claims that another one claims too — the clash of
        // §12, marked on both Workouts because either could give way.
        const clash = issues.find(
          (issue) =>
            issue.code === 'suggested_day_shared' &&
            issue.paths.some((path) => path[1] === 'workouts' && path[2] === index),
        );
        const claimedElsewhere = new Set(
          file.routine.workouts.flatMap((other, otherIndex) =>
            otherIndex === index ? [] : other.suggested_days,
          ),
        );
        const errorId = `${fieldId(workoutPath(index))}-days-error`;

        return (
          // The key belongs on `Card`, the outermost element this map returns.
          // On the `<section>` inside it, React never sees it and warns.
          <Card asChild className="focus-visible:outline-none" key={`${workout.name}-${index}`}>
            <section id={fieldId(workoutPath(index))} tabIndex={-1}>
            <div className="flex flex-col gap-1">
              <h2 className="type-title">{workout.name}</h2>
              <p className="type-measure-sm text-ink-3">
                {workout.exercises.length}{' '}
                {workout.exercises.length === 1 ? 'exercise' : 'exercises'}
              </p>
            </div>

            <div
              aria-describedby={clash === undefined ? undefined : errorId}
              aria-label={`Suggested days for ${workout.name}`}
              className="grid grid-cols-4 gap-2"
              role="group"
            >
              {WEEKDAYS.map(({ day, short }) => {
                const on = workout.suggested_days.includes(day);
                const conflicted = on && claimedElsewhere.has(day);
                return (
                  <button
                    aria-label={dayName(day)}
                    aria-pressed={on}
                    className={cn(
                      'flex min-h-12 items-center justify-center rounded-control type-label',
                      PRESS,
                      FOCUS_RING,
                      conflicted
                        ? 'bg-missed-ink text-on-fill'
                        : on
                          ? 'bg-planned-ink text-on-fill'
                          : 'bg-card text-ink-3 shadow-dome hover:shadow-dome-lift',
                    )}
                    key={day}
                    onClick={() => onToggleDay(index, day)}
                    type="button"
                  >
                    {short}
                  </button>
                );
              })}
            </div>

            {clash !== undefined && (
              <p className="type-caption text-missed-ink" id={errorId}>
                {describeIssue(clash, undefined)}
              </p>
            )}

            {workout.suggested_days.length === 0 && (
              <p className="type-caption text-ink-3">
                No day chosen. This Workout lands on no date — you can still put it on
                the calendar yourself later.
              </p>
            )}
            </section>
          </Card>
        );
      })}

      <section className={WELL}>
        <span className={LABEL}>what this generates</span>
        {placements.length === 0 ? (
          <p className="type-body-sm text-ink-2">
            No sessions yet. Choose at least one day above, and they appear here.
          </p>
        ) : (
          <>
            <p className="type-readout">
              {placements.length} {placements.length === 1 ? 'session' : 'sessions'}
            </p>
            <p className="type-measure-sm text-ink-3">
              {first !== undefined && last !== undefined
                ? `${longDate(first)} → ${longDate(last)}`
                : ''}
            </p>
            <p className="type-caption text-ink-2">
              Days are placed from today, so this week only carries the ones that have
              not passed yet.
            </p>
          </>
        )}
        <div className="flex flex-wrap gap-2">
          <span className={chip('planned')}>
            {weeks} {weeks === 1 ? 'week' : 'weeks'}
          </span>
          <span className={chip('neutral')}>
            {file.routine.workouts.length}{' '}
            {file.routine.workouts.length === 1 ? 'workout' : 'workouts'}
          </span>
        </div>
      </section>
    </>
  );
}

/**
 * The Placements this file would generate today.
 *
 * `generatePlacements` reads only a Workout's `suggestedDays` and the routine's
 * `weeks`, so the preview builds the smallest Workouts that satisfy it rather
 * than mapping the whole file — no ids are generated and nothing is written.
 */
function previewPlacements(file: RoutineFile, today: LocalDate) {
  const workouts: Workout[] = file.routine.workouts.map((workout, index) => ({
    id: toId<WorkoutId>(`preview-${index}`),
    routineId: toId<RoutineId>('preview'),
    name: workout.name,
    suggestedDays: workout.suggested_days,
    order: index,
  }));

  return generatePlacements({ workouts, weeks: file.routine.weeks, anchorDate: today });
}

function dayName(day: Weekday): string {
  return day.charAt(0).toUpperCase() + day.slice(1);
}

function longDate(date: LocalDate): string {
  return parseLocalDate(date).toLocaleDateString(undefined, {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
  });
}
