/**
 * The class vocabulary of the Dose Card, in one place (DESIGN.md).
 *
 * Every value here resolves to a token generated by `src/styles/theme.css`:
 * no colour, radius, shadow or type literal appears in this file or in any
 * component that imports it. The two arbitrary values that do appear — the
 * button's `22px` inset and the focus halo — are quoted verbatim from
 * `DESIGN.md:772-806`, which names them as the exceptions the Token-Only Rule
 * allows.
 *
 * Depth carries meaning here, so the names do too: `DOME` is pressable, an
 * inset well is a cavity, `shadow-lift` is a container sitting on the board.
 *
 * This file is the vocabulary; `src/components/ui/` is where it is worn. A
 * primitive that arrived from shadcn imports its face from here rather than
 * carrying one of its own, which is what keeps DESIGN.md the only place a
 * colour, a radius or an elevation is decided.
 */

import { cn } from '@/lib/utils';

/* ── Page ──────────────────────────────────────────────────────────────── */

/** The board. `dvh` rather than `vh` so a phone's URL bar cannot clip it. */
export const SCREEN = 'relative min-h-dvh bg-board text-ink';

/**
 * One vertical column of cards, authored at 390px and capped so a desktop
 * window does not stretch a phone layout across a monitor (DESIGN.md Layout).
 * A screen carrying the fixed action bar adds `pb-48` to clear it.
 */
export const COLUMN = 'relative mx-auto flex w-full max-w-lg flex-col gap-4 px-4 pt-6 pb-12';

/* ── Surfaces ──────────────────────────────────────────────────────────── */

/**
 * A card on the board: a solid near-white face with a soft drop under it. No
 * border — with the board a full step darker, the shadow separates it, and a
 * hairline on top of that reads as a second outline.
 */
export const CARD = 'bg-card text-ink rounded-card shadow-lift p-5 flex flex-col gap-4';

/** A row that is its own object on the board — same face, a shallower drop. */
export const PANEL_CARD = 'bg-card text-ink rounded-card shadow-dome p-4 flex flex-col gap-3';

/**
 * An inert region on the board: an empty state, a readout, something settled.
 * Same face as a card and no shadow at all — flat means there is nothing here
 * to press. It never sits inside a card; board → card → well would be three
 * stacked surfaces for what one can hold, which is the nested-card mistake
 * wearing a different name.
 */
export const WELL = 'bg-card text-ink rounded-card p-4 flex flex-col gap-3';

/**
 * How a card holds a list. Rows are separated by a hairline and by space, never
 * by a second surface (DESIGN.md: cards never nest).
 */
export const ROW_LIST = 'flex flex-col divide-y divide-rule';
export const ROW = 'flex flex-col gap-1.5 py-4 first:pt-0 last:pb-0';

/** A block inside a card set off from what precedes it, without a new surface. */
export const RULED = 'flex flex-col gap-3 border-t border-rule pt-4';

/* ── Type ──────────────────────────────────────────────────────────────── */

export const LABEL = 'type-label text-ink-3';

/* ── Controls ──────────────────────────────────────────────────────────── */

/**
 * The focus halo: a 1px Instrument Blue ring inside a 3px wash, quoted from
 * `DESIGN.md:781`. The one arbitrary shadow the Token-Only Rule allows, and it
 * is written once so every focusable control in the app wears the same one.
 */
export const FOCUS_RING =
  'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-planned ' +
  'focus-visible:shadow-[0_0_0_3px_var(--color-planned-wash)]';

/**
 * The press: 110ms, once, on every control. The system's only motion moment.
 *
 * `scale` and `translate` are named because Tailwind v4 writes neither through
 * `transform` any more: `scale-[.975]` compiles to `scale: .975` and
 * `-translate-y-0.5` to `translate: …`, each its own animatable property. This
 * list is an arbitrary value, so it takes no expansion — it *is* the literal
 * `transition-property`. Naming only `transform` therefore transitioned nothing
 * the press or the hover lift actually change, and the system's one motion
 * moment snapped in both directions on every control in the app. The *named*
 * `transition-transform` utility does expand to all four, which is why the
 * chevrons and the switch thumb were never affected by this.
 */
export const PRESS =
  'transition-[box-shadow,transform,scale,translate,background-color] duration-[110ms] ease-snap active:scale-[.975]';

/**
 * A button is fully round. `rounded-chip` is the same 999px the cells and the
 * status pills already use — the shape that says "this is a whole object", not
 * a panel with softened corners. Nothing else moves to it: a day cell, a nav
 * item and a field keep the radius §Shapes gives them, so the pill stays the
 * mark of something you press.
 */
export const BUTTON_BASE =
  `inline-flex items-center justify-center gap-2 min-h-12 rounded-chip type-title ${PRESS} ${FOCUS_RING} disabled:pointer-events-none`;

/** Disabled goes flat rather than fading out: no shadow means nothing to press. */
const BUTTON_DISABLED = 'disabled:bg-well disabled:text-ink-3 disabled:shadow-none';

export const BUTTON_VARIANT = {
  /** Green, because the primary action is always "record what happened". */
  primary: `bg-actual-ink text-on-fill shadow-lift hover:bg-actual-deep ${BUTTON_DISABLED}`,
  /** A dome: solid white, raised, lifting on hover. */
  secondary: `bg-card text-ink shadow-dome hover:shadow-dome-lift hover:-translate-y-0.5 ${BUTTON_DISABLED}`,
  ghost: 'bg-transparent text-planned-ink hover:bg-planned-wash disabled:text-ink-3',
  danger: `bg-missed-ink text-on-fill shadow-lift hover:bg-missed-deep ${BUTTON_DISABLED}`,
  /**
   * Navigation, not action: reordering, paging a month. Instrument Blue is
   * already this system's navigation hue — the active nav item and the focus
   * ring are both blue — so a light wash of it reads as "move", never as
   * "record".
   *
   * The wash alone is only 1.13:1 against the panel, so the boundary is carried
   * by the ring at 4.97:1, which is what makes the control findable. This is
   * the visible cousin of glass: on a flat white board a real backdrop-filter
   * has nothing to blur (the Visible-Glass Rule), so the light tinted face and
   * the soft dome pair do the work instead.
   */
  nav: `bg-planned-wash text-planned-ink ring-1 ring-planned shadow-dome hover:bg-card hover:shadow-dome-lift hover:-translate-y-0.5 ${BUTTON_DISABLED}`,
  /**
   * The way out of a destructive confirm. It needs a body of its own so it is
   * not a hole in the card, and it must stay subordinate to the red beside it,
   * so it takes the neutral cavity colour with a muted ring rather than a hue.
   */
  quiet: `bg-well text-ink ring-1 ring-ink-3 shadow-dome hover:bg-card ${BUTTON_DISABLED}`,
} as const;

export const BUTTON_SIZE = {
  control: 'px-[22px] py-3.5',
  compact: 'px-4 py-2 type-body-sm',
  /** Square, for an icon that carries an `aria-label` instead of a word. */
  icon: 'w-12 px-0',
  block: 'w-full px-6',
} as const;

export type ButtonVariant = keyof typeof BUTTON_VARIANT;
export type ButtonSize = keyof typeof BUTTON_SIZE;

/**
 * A tab trigger is a dome; the current one is pressed in and filled with
 * Instrument Blue, the hue that owns "what the programme said".
 *
 * Two forms of one thing: `TAB_TRIGGER` reads the state off the element, which
 * is what a Radix trigger publishes, and `tab()` takes it as an argument for
 * the places that own the state themselves.
 */
const TAB_BASE =
  `inline-flex shrink-0 items-center gap-2 min-h-12 rounded-control px-4 type-body-sm ${PRESS} ${FOCUS_RING}`;

const TAB_REST = 'bg-card text-ink-2 shadow-dome hover:shadow-dome-lift';
const TAB_ACTIVE = 'bg-planned-ink text-on-fill shadow-none';

export const TAB_TRIGGER = cn(
  TAB_BASE,
  TAB_REST,
  'data-[state=active]:bg-planned-ink data-[state=active]:text-on-fill data-[state=active]:shadow-none',
);

export function tab(active: boolean, extra?: string): string {
  return cn(TAB_BASE, active ? TAB_ACTIVE : TAB_REST, extra);
}

/** A row in a menu: full-bleed, 48 tall, highlighted by the accent wash. */
export const MENU_ITEM = cn(
  'flex min-h-12 w-full cursor-default items-center gap-3 rounded-control px-3 text-left type-body-sm',
  'select-none outline-none focus:bg-well data-[highlighted]:bg-well',
  'data-[disabled]:pointer-events-none data-[disabled]:text-ink-3',
  FOCUS_RING,
);

/* ── Fields ────────────────────────────────────────────────────────────── */

/**
 * A field takes the well: DESIGN.md already called it "a cavity something goes
 * into", and a white plane on a white card was that sentence unpainted. The
 * hairline stays — it is what the invalid ring replaces — but the tint is what
 * finds the control now, the same tint the weeks readout wears.
 */
export const FIELD_BASE = `w-full min-h-12 rounded-field bg-well text-ink ring-1 ring-edge px-3 ${FOCUS_RING}`;

/** Invalid adds a ring in Errata Red — the hue that owns a validation error. */
export function field(invalid: boolean, extra?: string): string {
  return cn(FIELD_BASE, invalid && 'ring-1 ring-missed', extra);
}

/* ── Status ────────────────────────────────────────────────────────────── */

const CHIP_TONE = {
  neutral: 'bg-panel text-ink-2 shadow-edge',
  planned: 'bg-planned-ink text-on-fill',
  actual: 'bg-actual-ink text-on-fill',
  missed: 'bg-missed-ink text-on-fill',
  /**
   * Derived Violet — a number nobody entered (DESIGN.md).
   *
   * The hue exists so a computed figure is never dressed as an observed one. It
   * had no chip until a progression suggestion and a session record needed to
   * sit beside sets that were actually performed, which is exactly the
   * distinction the fifth hue was reserved for.
   */
  progress: 'bg-progress-ink text-on-fill',
} as const;

export type ChipTone = keyof typeof CHIP_TONE;

/** Status only, never an action (DESIGN.md Chips). */
export function chip(tone: ChipTone = 'neutral', extra?: string): string {
  return cn(
    'inline-flex items-center gap-1.5 rounded-chip type-label px-3 py-1.5',
    CHIP_TONE[tone],
    extra,
  );
}

/** A solid band in the hue of what it is announcing, with white text. */
export function alert(tone: 'missed' | 'planned' = 'missed', extra?: string): string {
  return cn(
    'flex items-start gap-3 rounded-control px-4 py-3 text-on-fill',
    tone === 'missed' ? 'bg-missed-ink' : 'bg-planned-ink',
    extra,
  );
}

/** The one place an icon's stroke weight is decided (DESIGN.md). */
export const ICON_STROKE = 1.75;

/* ── Gym mode ──────────────────────────────────────────────────────────── */

/**
 * The Dome — one dome is one Set (DESIGN.md §Components).
 *
 * The only component that carries all five hues, so it is the one place where
 * state and colour are bound together, and it is bound once. A circle, because
 * a set is a whole object; 96px when live so it is the largest thing on screen;
 * `animate-breathe` while it waits to be performed. `logged` and `missed` are
 * flat and inert — what happened cannot be pressed again.
 */
const DOME_STATE = {
  planned: 'bg-card text-planned-ink shadow-dome ring-2 ring-planned-wash',
  live: 'bg-live text-on-live shadow-dome-lift animate-breathe',
  logged: 'bg-actual-ink text-on-fill shadow-none',
  suggested: 'bg-progress text-on-fill shadow-dome-lift',
  missed: 'bg-missed-ink text-on-fill shadow-none',
  locked: 'bg-well text-ink-3 shadow-none',
  /**
   * Not a Set — the offer of one. It is the only dome drawn as an outline
   * rather than a body, because there is nothing there yet: a solid circle
   * would claim a set exists. Dashed says "this could be one".
   */
  add: 'bg-transparent text-ink-3 border-2 border-dashed border-edge hover:border-planned hover:text-planned-ink shadow-none',
} as const;

const DOME_SIZE = {
  compact: 'size-[60px] type-body-sm',
  default: 'size-[76px] type-title',
  live: 'size-[96px] type-readout',
} as const;

export type DomeState = keyof typeof DOME_STATE;
export type DomeSize = keyof typeof DOME_SIZE;

export function dome(state: DomeState, size: DomeSize = 'default', extra?: string): string {
  return cn(
    'inline-flex shrink-0 flex-col items-center justify-center gap-0.5 rounded-cell leading-none',
    PRESS,
    FOCUS_RING,
    'disabled:pointer-events-none',
    DOME_STATE[state],
    DOME_SIZE[size],
    extra,
  );
}

/**
 * The stepper beside a readout: a small dome carrying one glyph. It adjusts a
 * value rather than recording one, so it takes the navigation face the month
 * pager already wears, not the green of "record what happened".
 */
export const STEPPER = cn(
  'inline-flex size-12 shrink-0 items-center justify-center rounded-cell',
  'bg-planned-wash text-planned-ink ring-1 ring-planned shadow-dome',
  'hover:bg-card hover:shadow-dome-lift',
  'disabled:bg-well disabled:text-ink-3 disabled:shadow-none disabled:ring-rule disabled:pointer-events-none',
  PRESS,
  FOCUS_RING,
);

/**
 * A weight / reps / RIR readout: the cavity the value sits in, flat, with the
 * number in Readout type and the unit named in the label above it
 * (DESIGN.md §Inputs).
 *
 * It holds a real input. DESIGN.md says adjustment is by steppers and not by
 * keyboard, and steppers are still the default path — but stepping 20 to 90 is
 * 28 presses, so the readout takes typing too. The two edit one value; see
 * `SetLogger`.
 */
export const READOUT = cn(
  // The three gym-mode readouts had no boundary at all — `bg-well` on `bg-card`
  // is 1.13:1, so the field a lifter aims a thumb at mid-set was findable only
  // by the label above it.
  'flex min-w-0 flex-1 flex-col items-center gap-0.5 rounded-field bg-well ring-1 ring-edge px-2 py-3',
  // The value inside is typed into as well as stepped, so the cavity takes the
  // focus halo on behalf of the borderless input it holds.
  'focus-within:ring-1 focus-within:ring-planned focus-within:shadow-[0_0_0_3px_var(--color-planned-wash)]',
);

/**
 * The number itself inside a readout: an input wearing the readout's face
 * rather than a field of its own, so typing and stepping are visibly the same
 * control rather than two that disagree.
 */
export const READOUT_INPUT =
  'w-full min-w-0 bg-transparent text-center type-readout text-ink outline-none';

/**
 * The rest timer: the one full-bleed coloured surface in the product. The
 * darker `live-ink` rather than `live`, so white Clock type clears it
 * (DESIGN.md §Rest timer).
 *
 * It docks to the bottom edge rather than taking a card in the column. Gym mode
 * hides the navigation (§21), so the thumb zone is free — and rest belongs to
 * the session, not to the exercise the column happens to be showing, so it has
 * no business pushing the set being logged down the screen.
 */
export const TIMER_SHELL =
  'fixed inset-x-0 bottom-0 z-20 overflow-hidden bg-live-ink text-on-fill shadow-lift';

/** The track along its top edge, and the rail that scales down inside it. */
export const TIMER_TRACK = 'absolute inset-x-0 top-0 h-1.5 bg-scrim';
export const TIMER_RAIL =
  'h-full origin-left bg-live-rail transition-transform duration-1000 ease-linear';
