/**
 * The class vocabulary of the Dose Card, in one place (DESIGN.md).
 *
 * Every value here resolves to a token generated by `src/styles/theme.css`:
 * no colour, radius, shadow or type literal appears in this file or in any
 * component that imports it. The two arbitrary values that do appear — the
 * button's `22px` inset and the focus halo — are quoted verbatim from
 * `DESIGN.md:772-806`, which names them as the exceptions the Token-Only Rule
 * allows.
 *
 * Depth carries meaning here, so the names do too: `DOME` is pressable, an
 * inset well is a cavity, `shadow-lift` is a container sitting on the board.
 */

import { cn } from '@/lib/utils';

/* ── Page ──────────────────────────────────────────────────────────────── */

/** The board. `dvh` rather than `vh` so a phone's URL bar cannot clip it. */
export const SCREEN = 'relative min-h-dvh bg-board text-ink';

/**
 * One vertical column of cards, authored at 390px and capped so a desktop
 * window does not stretch a phone layout across a monitor (DESIGN.md Layout).
 * A screen carrying the fixed action bar adds `pb-48` to clear it.
 */
export const COLUMN = 'relative mx-auto flex w-full max-w-lg flex-col gap-4 px-4 pt-6 pb-12';

/* ── Surfaces ──────────────────────────────────────────────────────────── */

/** A card on the board. Cards never nest — a region inside one is a `WELL`. */
export const CARD =
  'bg-card text-ink rounded-card border border-rule shadow-lift p-5 flex flex-col gap-4';

/** The quiet support surface, for a row in a list of many. */
export const PANEL_CARD =
  'bg-panel text-ink rounded-card border border-rule p-4 flex flex-col gap-3';

/** A cavity in the board: readouts, groups of fields, empty states. */
export const WELL = 'bg-well rounded-field inset-shadow-pressed p-4 flex flex-col gap-3';

/* ── Type ──────────────────────────────────────────────────────────────── */

export const LABEL = 'type-label text-ink-3';

/* ── Controls ──────────────────────────────────────────────────────────── */

/**
 * The focus halo: a 1px Instrument Blue ring inside a 3px wash, quoted from
 * `DESIGN.md:781`. The one arbitrary shadow the Token-Only Rule allows, and it
 * is written once so every focusable control in the app wears the same one.
 */
export const FOCUS_RING =
  'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-planned ' +
  'focus-visible:shadow-[0_0_0_3px_var(--color-planned-wash)]';

/** The press: 110ms, once, on every control. The system's only motion moment. */
export const PRESS =
  'transition-[box-shadow,transform,background-color] duration-[110ms] ease-snap active:scale-[.975]';

const BUTTON_BASE =
  `inline-flex items-center justify-center gap-2 min-h-12 rounded-control type-title ${PRESS} ${FOCUS_RING} disabled:pointer-events-none`;

/** Disabled sinks into the board rather than fading out (DESIGN.md Buttons). */
const BUTTON_DISABLED =
  'disabled:bg-well disabled:text-ink-3 disabled:shadow-none disabled:inset-shadow-pressed';

const BUTTON_VARIANT = {
  /** Green, because the primary action is always "record what happened". */
  primary: `bg-actual-ink text-on-fill shadow-lift hover:bg-actual-deep ${BUTTON_DISABLED}`,
  /** A dome: solid white, raised, lifting on hover. */
  secondary: `bg-card text-ink shadow-dome hover:shadow-dome-lift hover:-translate-y-0.5 ${BUTTON_DISABLED}`,
  ghost: 'bg-transparent text-planned-ink hover:bg-planned-wash disabled:text-ink-3',
  danger: `bg-missed-ink text-on-fill shadow-lift hover:bg-missed-deep ${BUTTON_DISABLED}`,
} as const;

const BUTTON_SIZE = {
  control: 'px-[22px] py-3.5',
  compact: 'px-4 py-2 type-body-sm',
  /** Square, for an icon that carries an `aria-label` instead of a word. */
  icon: 'w-12 px-0',
  block: 'w-full px-6',
} as const;

export type ButtonVariant = keyof typeof BUTTON_VARIANT;
export type ButtonSize = keyof typeof BUTTON_SIZE;

/** The 48 Rule lives in the base, never at the call site. */
export function button(
  variant: ButtonVariant = 'primary',
  size: ButtonSize = 'control',
  extra?: string,
): string {
  return cn(BUTTON_BASE, BUTTON_VARIANT[variant], BUTTON_SIZE[size], extra);
}

/**
 * A tab trigger is a dome; the current one is pressed in and filled with
 * Instrument Blue, the hue that owns "what the programme said".
 */
export function tab(active: boolean, extra?: string): string {
  return cn(
    'inline-flex shrink-0 items-center gap-2 min-h-12 rounded-control px-4 type-body-sm',
    PRESS,
    FOCUS_RING,
    active
      ? 'bg-planned-ink text-on-fill inset-shadow-sunk'
      : 'bg-card text-ink-2 shadow-dome hover:shadow-dome-lift',
    extra,
  );
}

/* ── Fields ────────────────────────────────────────────────────────────── */

/** A field is a cavity something goes into: white, recessed, no border. */
const FIELD_BASE = `w-full min-h-12 rounded-field bg-field text-ink inset-shadow-pressed px-3 ${FOCUS_RING}`;

/** Invalid adds a ring in Errata Red — the hue that owns a validation error. */
export function field(invalid: boolean, extra?: string): string {
  return cn(FIELD_BASE, invalid && 'ring-1 ring-missed', extra);
}

/* ── Status ────────────────────────────────────────────────────────────── */

const CHIP_TONE = {
  neutral: 'bg-panel text-ink-2 shadow-edge',
  planned: 'bg-planned-ink text-on-fill',
  actual: 'bg-actual-ink text-on-fill',
  missed: 'bg-missed-ink text-on-fill',
} as const;

export type ChipTone = keyof typeof CHIP_TONE;

/** Status only, never an action (DESIGN.md Chips). */
export function chip(tone: ChipTone = 'neutral', extra?: string): string {
  return cn(
    'inline-flex items-center gap-1.5 rounded-chip type-label px-3 py-1.5',
    CHIP_TONE[tone],
    extra,
  );
}

/** A solid band in the hue of what it is announcing, with white text. */
export function alert(tone: 'missed' | 'planned' = 'missed', extra?: string): string {
  return cn(
    'flex items-start gap-3 rounded-control px-4 py-3 text-on-fill',
    tone === 'missed' ? 'bg-missed-ink' : 'bg-planned-ink',
    extra,
  );
}

/** The one place an icon's stroke weight is decided (DESIGN.md). */
export const ICON_STROKE = 1.75;
