/**
 * The harness's shared class strings (REQ-083): every colour, radius, shadow
 * and type style is a token utility generated by `src/styles/theme.css`. No
 * literal value appears here or in any harness component.
 */

export const PANEL = 'bg-card text-ink rounded-frame shadow-dome p-5 flex flex-col gap-4';
export const CARD = 'bg-panel border border-rule rounded-card p-3 flex flex-col gap-2';
export const WELL = 'bg-well rounded-field p-2 flex flex-col gap-1';
export const LABEL = 'type-label text-ink-3';
export const BUTTON =
  'bg-actual-ink text-on-fill rounded-control shadow-lift type-label px-4 py-2 disabled:opacity-40';
export const BUTTON_QUIET =
  'bg-card text-ink-2 border border-rule rounded-control type-label px-3 py-2 disabled:opacity-40';
export const INPUT = 'bg-field text-ink border border-rule rounded-field type-measure px-2 py-1';
