/**
 * Which catalog movements ship with a drawing (§11.12).
 *
 * The files live in `public/exercise-art/<id>.svg`, one per id, so this set is
 * the whole index — a name is a path. It exists because a missing mask image is
 * not a missing image: CSS draws the element unmasked, which is a solid block
 * of colour where a figure should be. Asking first is cheaper than that.
 *
 * 280 of the catalog's 299 rows have one. The 19 that do not render with no
 * figure, which is honest. An Exercise a lifter created is never in here: its
 * id is generated, and nothing shipped in the build can be named after it.
 *
 * GENERATED by `pnpm art` from the contents of that directory. Add a drawing
 * there and run it again rather than editing this list — the directory is the
 * truth, and a hand-edited entry with no file behind it draws that solid block.
 */

const DRAWN: ReadonlySet<string> = new Set([
  'ab-wheel-rollout', 'active-hang', 'archer-push-up', 'arnold-press', 'assisted-chin-up', 'assisted-dip',
  'assisted-pistol-squat', 'assisted-pull-up', 'back-extension', 'back-squat', 'band-pull-apart',
  'banded-clamshell', 'banded-dead-bug', 'banded-donkey-kick', 'banded-face-pull', 'banded-fire-hydrant',
  'banded-frog-pump', 'banded-glute-bridge', 'banded-hip-thrust', 'banded-kickback', 'banded-lat-pulldown',
  'banded-lateral-walk', 'banded-monster-walk', 'banded-pallof-press', 'banded-row', 'banded-seated-hip-abduction',
  'banded-squat', 'banded-standing-hip-abduction', 'banded-woodchop', 'barbell-glute-bridge',
  'barbell-row', 'barbell-shrug', 'bear-crawl', 'bear-plank', 'belt-squat', 'bench-dip', 'bench-press',
  'bent-over-rear-delt-raise', 'bicycle-crunch', 'bird-dog', 'bodyweight-squat', 'bulgarian-split-squat',
  'burpee', 'cable-crunch', 'cable-curl', 'cable-fly', 'cable-front-raise', 'cable-kickback',
  'cable-lateral-raise', 'cable-pallof-hold', 'cable-pull-through', 'cable-rear-delt-fly', 'cable-standing-hip-abduction',
  'cable-standing-hip-adduction', 'cable-woodchop', 'captains-chair-knee-raise', 'chair-dip',
  'chest-supported-row', 'chin-up', 'clamshell', 'close-grip-bench-press', 'close-grip-lat-pulldown',
  'commando-pull-up', 'concentration-curl', 'conventional-deadlift', 'copenhagen-plank', 'cossack-squat',
  'crab-walk', 'crunch', 'curtsy-lunge', 'dead-bug', 'dead-hang', 'decline-bench-press', 'decline-dumbbell-press',
  'decline-push-up', 'decline-sit-up', 'deficit-reverse-lunge', 'diamond-push-up', 'dip', 'donkey-calf-raise',
  'donkey-kick', 'doorway-row', 'drag-curl', 'dragon-flag', 'dumbbell-bench-press', 'dumbbell-curl',
  'dumbbell-curtsy-lunge', 'dumbbell-fly', 'dumbbell-glute-bridge', 'dumbbell-hip-thrust', 'dumbbell-lateral-lunge',
  'dumbbell-romanian-deadlift', 'dumbbell-row', 'dumbbell-shrug', 'dumbbell-side-bend', 'dumbbell-skull-crusher',
  'dumbbell-sumo-deadlift', 'dumbbell-sumo-squat', 'explosive-push-up', 'ez-bar-curl', 'face-pull',
  'farmers-walk', 'fast-feet', 'feet-elevated-pike-push-up', 'fire-hydrant', 'flutter-kick',
  'forward-lunge', 'frog-pump', 'front-foot-elevated-split-squat', 'front-raise', 'front-squat',
  'glute-bridge', 'glute-bridge-march', 'glute-focused-back-extension', 'goblet-squat', 'good-morning',
  'hack-squat', 'half-burpee', 'half-kneeling-pallof-press', 'hammer-curl', 'handstand-push-up',
  'hanging-knee-raise', 'hanging-leg-raise', 'heel-elevated-goblet-squat', 'heel-tap', 'high-knees',
  'hindu-push-up', 'hip-abduction', 'hip-adduction-machine', 'hip-airplane', 'hip-thrust', 'hollow-body-hold',
  'hollow-rock', 'inchworm', 'incline-bench-press', 'incline-cable-fly', 'incline-dumbbell-curl',
  'incline-dumbbell-press', 'incline-push-up', 'inverted-row', 'jump-squat', 'jumping-jack',
  'kettlebell-romanian-deadlift', 'kettlebell-swing', 'knee-push-up', 'l-sit-hold', 'l-sit-pull-up',
  'landmine-press', 'landmine-romanian-deadlift', 'landmine-squat', 'lat-pulldown', 'lateral-lunge',
  'lateral-raise', 'lateral-shuffle', 'leg-extension', 'leg-press', 'leg-press-calf-raise',
  'lying-hamstring-walkout', 'lying-leg-curl', 'lying-leg-raise', 'machine-chest-press', 'machine-glute-kickback',
  'machine-lateral-raise', 'machine-row', 'machine-shoulder-press', 'meadows-row', 'mountain-climber',
  'negative-pull-up', 'neutral-grip-pull-up', 'nordic-curl', 'one-arm-dumbbell-row', 'overhead-press',
  'overhead-triceps-extension', 'pallof-press', 'pec-deck', 'pendlay-row', 'pike-push-up', 'pistol-squat',
  'plank', 'plank-jack', 'plank-shoulder-tap', 'plate-front-raise', 'preacher-curl', 'prone-t-raise',
  'prone-y-raise', 'pull-up', 'push-press', 'push-up', 'push-up-shoulder-tap', 'rack-pull',
  'rear-delt-fly', 'reverse-crunch', 'reverse-curl', 'reverse-hyperextension', 'reverse-lunge',
  'reverse-pec-deck', 'reverse-snow-angel', 'romanian-deadlift', 'rope-hammer-curl', 'rope-tricep-pushdown',
  'russian-twist', 'scapular-pull-up', 'scapular-push-up', 'seal-jack', 'seated-cable-row',
  'seated-calf-raise', 'seated-dumbbell-press', 'seated-knee-tuck', 'seated-leg-curl', 'shrimp-squat',
  'side-lying-hip-abduction', 'side-lying-leg-raise', 'side-plank', 'side-plank-hip-dip', 'single-arm-cable-row',
  'single-arm-dumbbell-tricep-extension', 'single-dumbbell-skullcrusher', 'single-leg-box-squat',
  'single-leg-calf-raise', 'single-leg-glute-bridge', 'single-leg-romanian-deadlift', 'sissy-squat',
  'skater-hop', 'skater-squat', 'skull-crusher', 'smith-machine-bench-press', 'smith-machine-bulgarian-split-squat',
  'smith-machine-hip-thrust', 'smith-machine-reverse-lunge', 'smith-machine-romanian-deadlift',
  'smith-machine-split-squat', 'smith-machine-squat', 'spider-curl', 'split-squat', 'sprawl',
  'squat-thrust', 'stability-ball-hamstring-curl', 'standing-calf-raise', 'standing-dumbbell-press',
  'step-down', 'step-up', 'straight-arm-pulldown', 'sumo-deadlift', 'superman', 'superman-hold',
  't-bar-row', 'toe-touch', 'towel-hamstring-curl', 'towel-pull-up', 'towel-row', 'trap-bar-deadlift',
  'triceps-kickback', 'triceps-pushdown', 'typewriter-push-up', 'upright-row', 'v-up', 'walking-lunge',
  'wall-handstand-push-up', 'wall-push-up', 'wall-sit', 'wall-walk', 'weighted-back-extension',
  'weighted-chin-up', 'weighted-crunch', 'weighted-decline-sit-up', 'weighted-dip', 'weighted-handstand-push-up',
  'weighted-hanging-knee-raise', 'weighted-hanging-leg-raise', 'weighted-inverted-row', 'weighted-neutral-grip-pull-up',
  'weighted-pistol-squat', 'weighted-pull-up', 'weighted-push-up', 'weighted-russian-twist',
  'weighted-single-leg-calf-raise', 'wide-grip-lat-pulldown', 'wide-push-up', 'wrist-curl',
  'wrist-extension',
]);

/** Whether `public/exercise-art/<id>.svg` exists for this Exercise. */
export function hasExerciseArt(id: string): boolean {
  return DRAWN.has(id);
}
