/**
 * Rebuilds `src/domain/catalog/art.ts` from what is in `public/exercise-art/`.
 *
 * Run it after adding or removing a drawing: `pnpm art`.
 *
 * The directory is the index — a file's name is the Exercise id it belongs to,
 * and this script only writes that fact down in a form the bundle can read. It
 * exists because the app cannot list a directory at runtime, and because a
 * missing mask image is not a missing image: CSS draws the element unmasked,
 * which is a solid block of colour where a figure should be.
 *
 * No dependencies, on purpose. Drawing the figures is somebody's tool of
 * choice; turning a directory listing into a `Set` is nine lines of `node:fs`,
 * and neither sharp nor potrace belongs in this app's lockfile for it.
 *
 * It also refuses the two mistakes that produce a page that looks broken rather
 * than a page that is missing a picture:
 *
 *   - a file whose name is not a catalog slug — a typo, or an Exercise a lifter
 *     created, which has a generated id and can never have shipped art;
 *   - an SVG with no `viewBox`, which `mask-size: contain` cannot scale.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const artDir = new URL('public/exercise-art/', root);
const dataFile = new URL('src/domain/catalog/data.ts', root);
const outFile = new URL('src/domain/catalog/art.ts', root);

const slugs = readdirSync(fileURLToPath(artDir))
  .filter((name) => name.endsWith('.svg'))
  .map((name) => name.slice(0, -'.svg'.length))
  .sort();

// The authored rows, read as text rather than imported: this is a plain node
// script and `data.ts` is TypeScript with a path alias in it.
const catalog = new Set(
  [...readFileSync(fileURLToPath(dataFile), 'utf8').matchAll(/^\s*\['([a-z0-9-]+)',/gm)].map(
    (match) => match[1],
  ),
);

const problems = [];
for (const slug of slugs) {
  if (!catalog.has(slug)) problems.push(`${slug}.svg — no catalog row has this id`);
  const svg = readFileSync(new URL(`${slug}.svg`, artDir), 'utf8');
  if (!svg.includes('viewBox')) problems.push(`${slug}.svg — no viewBox, so it cannot scale`);
}

if (problems.length > 0) {
  console.error(`${problems.length} drawing(s) rejected:\n  ${problems.join('\n  ')}`);
  process.exit(1);
}

const lines = [];
let row = [];
for (const slug of slugs) {
  row.push(`'${slug}',`);
  if (row.join(' ').length > 88) {
    lines.push(`  ${row.join(' ')}`);
    row = [];
  }
}
if (row.length > 0) lines.push(`  ${row.join(' ')}`);

const missing = [...catalog].filter((slug) => !slugs.includes(slug));

writeFileSync(
  fileURLToPath(outFile),
  `/**
 * Which catalog movements ship with a drawing (§11.12).
 *
 * The files live in \`public/exercise-art/<id>.svg\`, one per id, so this set is
 * the whole index — a name is a path. It exists because a missing mask image is
 * not a missing image: CSS draws the element unmasked, which is a solid block
 * of colour where a figure should be. Asking first is cheaper than that.
 *
 * ${slugs.length} of the catalog's ${catalog.size} rows have one. The ${missing.length} that do not render with no
 * figure, which is honest. An Exercise a lifter created is never in here: its
 * id is generated, and nothing shipped in the build can be named after it.
 *
 * GENERATED by \`pnpm art\` from the contents of that directory. Add a drawing
 * there and run it again rather than editing this list — the directory is the
 * truth, and a hand-edited entry with no file behind it draws that solid block.
 */

const DRAWN: ReadonlySet<string> = new Set([
${lines.join('\n')}
]);

/** Whether \`public/exercise-art/<id>.svg\` exists for this Exercise. */
export function hasExerciseArt(id: string): boolean {
  return DRAWN.has(id);
}
`,
);

console.log(`art.ts: ${slugs.length} drawings, ${missing.length} catalog rows without one`);
